name: VIEW_MODEL_PROJECT_IDENTIFIER_QW32
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/colors/alerts.xml
      - assets/colors/neutrals.xml
      - assets/colors/primary.xml
      - assets/colors/secondary.xml
      - assets/colors/specials.xml

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dio: ^5.2.1+1
  logger: ^2.3.0
  talker_dio_logger: ^4.2.3
  shake_detector: ^0.1.1
  talker_flutter: ^4.2.0

  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  get_it: ^8.0.0
  get_storage: ^2.1.1

  intl: ^0.19.0

  provider: ^6.1.2
  focus_detector: ^2.0.1

  awesome_dialog: ^3.2.1
  adaptive_dialog: ^2.1.0
  top_snackbar_flutter: ^3.1.0

  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  flutter_gen: ^5.5.0+1
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  envied_generator: ^0.5.4+1
# flutter_launcher_icons:
#   android: true
#   image_path_android: "assets/images/app_icon_android.png"
#   image_path_ios: "assets/images/app_icon_ios.png"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/images/app_icon_android.png"
#   ios: true

# flutter_native_splash:
#   color: "#F7F6F3"
#   image: assets/images/splash_image.png

#   android_12:
#     image: assets/images/splash_image_android_12.png
#     icon_background_color: "#F7F6F3"

#   web: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400